### PR TITLE
remove the requirements for the symfony version so it works for every version

### PR DESCRIPTION
**Pull request by MaximeThoonsen**

### CODE REVIEW

**Comment by MaximeThoonsen** [comment]
@cravler Is it ok for you ?

**Comment by cravler** [comment]
https://github.com/cravler/CravlerMaxMindGeoIpBundle/commit/947f0a19c4c47477db49ce90e385ab417f3a82d7

**Comment by MaximeThoonsen** [comment]
@cravler It will work for my project as it is sf3 but what about 2.7 version ?
Thanks anyway and hppy new year =)

**Comment by cravler** [comment]
https://getcomposer.org/doc/articles/versions.md#tilde

**Comment by MaximeThoonsen** [comment]
@cravler So it's perfect and ... I learn something this morning =)

**Pull request closed without merging**
